# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Modern C++
author: Krystian Piękoś - Infotraining
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: cpp-modern.tex

# sphinx:
#   config:
#     mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# # Information about where the book exists on the web
# repository:
#   url: https://github.com/infotraining/cpp-20  # Online location of your book
#   path_to_book: "book_pl"  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false

# Configure your Binder links, such as the URL of the BinderHub.
# launch_buttons:
#   binderhub_url             : https://mybinder.org

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - deflist
    - dollarmath